name: Setup 
description: Setup NoisePy for testing
runs:
  using: composite
  steps:
    - name: Checkout Repo
      uses: actions/checkout@v3.3.0
    - name: Setup Python
      uses: actions/setup-python@v4.5.0
      with:
        python-version: 3.8
    - name: Setup MPI
      uses: mpi4py/setup-mpi@v1
    - name: Install project
      shell: bash
      run: |
        python -m pip install --upgrade pip
        pip install "."