- name: Setup Python
  uses: actions/setup-python@v4.5.0
  with:
    python-version: ${{inputs.python-version}}
- name: Setup pip
  shell: sh
  run: |
    python3 -m ensurepip
    pip3 install --upgrade pip
- name: Install mpi4py
  shell: sh
  run: pip install mpi4py
- name: Setup MPI
  if: ${{ inputs.mpi == 'true' }}
  uses: mpi4py/setup-mpi@v1
- name: Install project no MPI
  if: ${{ inputs.mpi == 'false' }}
  shell: sh
  run: pip install ".[dev,aws]"
- name: Install project MPI
  if: ${{ inputs.mpi == 'true' }}
  shell: sh
  run: pip install ".[dev,mpi,aws]"
