name: Setup
description: Setup NoisePy for testing
inputs:
  python-version:
    required: true
    description: Python version to install
runs:
  using: composite
  steps:
    - name: Setup Python
      uses: actions/setup-python@v4.5.0
      with:
        python-version: ${{inputs.python-version}}
    - name: Setup MPI
      uses: mpi4py/setup-mpi@v1
    - name: Install project
      shell: sh
      run: |
        python3 -m ensurepip
        pip3 install --upgrade pip
        pip install ".[dev]"
