# config for codecov

coverage:
  status:

    # set commit status if relative change of whole project coverage
    # exceeds threshold
    project:
      default:
        target: auto
        threshold: 0
        set_pending: yes
        if_no_uploads: error
        if_not_found: error
        if_ci_failed: error

    # not exactly sure in what cases this commit status is triggered..
    changes:
      default:
        enabled: no

# no comments in PRs
comment: off
