# config for codecov

codecov: 
  token: 5b43bc70-96b0-4bbc-abe3-e3c3584db624

coverage:
  status:

    # set commit status if relative change of whole project coverage
    # exceeds threshold
    project:
      default:
        target: auto
        threshold: 0
        set_pending: yes
        if_no_uploads: error
        if_not_found: error
        if_ci_failed: error

    # set commit status, if coverage of diff is below target threshold
    patch:
      default:
        target: 90
        set_pending: yes
        base: auto
        if_no_uploads: error
        if_not_found: error
        if_ci_failed: error

    # not exactly sure in what cases this commit status is triggered..
    changes:
      default:
        enabled: no

# no comments in PRs
comment: off
