acorr_only: false
cc_len: 1800
cc_method: xcorr
channels: [BHE, BHN, BHZ]
client_url_key: SCEDC
correction: false
correction_csv: null
down_list: false
end_date: '2019-01-02T00:00:00Z'
freq_norm: rma
freqmax: 2.0
freqmin: 0.05
inc_hours: 24
keep_substack: false
lamax: 36.0
lamin: 31.0
lomax: -115.0
lomin: -122.0
max_over_std: 10
maxlag: 200
ncomp: 3
net_list: [CI]
respdir: null
rm_resp: inv
rm_resp_out: VEL
rotation: true
samp_freq: 20.0
single_freq: true
smooth_N: 10
smoothspect_N: 10
stack_method: linear
start_date: '2019-01-01T00:00:00Z'
stations: ['*']
stations_file: null
stationxml: false
step: 450.0
storage_options: {}
substack: false
substack_len: 1800
time_norm: no
xcorr_only: true
