name: noisepy-seis
channels:
  - conda-forge
  - nodefaults
dependencies:
  - python=3.8
  - h5py
  - mpi4py
  - numba
  - pandas
  - pyasdf
  - pycwt
  - diskcache
  - pip
  - pip:
    - "DateTimeRange==2.0.0"
    - "pyasdf>=0.7.5"
    - "pycwt>=0.3.0a22"
    - "diskcache>=5.5"